import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/layouts/Header'
import Footer from '@/components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function Home({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <main className = 'px-28'>
         <Header />
        {children}
         <Footer />
         </main>
        </body>
    </html>
  )
}

